project:
  type: book

book:
  title: "book"
  author: "Norah Jones"
  date: "12/16/2024"
  chapters:
    - index.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



